update=3/8/2009-05:41:59
last_client=cvpcb
[general]
version=1
RootSch=Mother.sch
BoardNm=Mother.brd
[cvpcb]
version=1
NetIExt=.net
[cvpcb/libraries]
EquName1=devcms
[common]
NetDir=
[pcbnew]
[pcbnew/libraries]
LibDir=
LibName1=./crystal
LibName2=supports
LibName3=connect
LibName4=discret
LibName5=pin_array
LibName6=divers
LibName7=libcms
LibName8=display
LibName9=valves
